version: '3'
services:

  postgres:
    image: dexels/dvdrental:1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  navajo:
    build:
      context: .
      args:
        VERSION: ${VERSION}
    ports:
      - "8181:8181"
    environment:
     - CLUSTER=demo
     - CONSOLE_PASS={sha-256}jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=
     - CONSOLE_USER=admin
     - FILE_REPOSITORY_DEPLOYMENT=develop
     - HAZELCAST_SIMPLE=true
     - INSTANCENAME=instance-1
     - LOGAPPENDERS=out,stdout
     - NAVAJO_REQUEST_TIMEOUT=5000
     - TENANT_MASTER=Tenant1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8181/status || exit 1"]
      interval: 1m00s
      timeout: 10s
      retries: 3

  mongodemo:
    image: mongo:latest
    ports:
      - "27017:27017"

  kafka:
    image: spotify/kafka:latest
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092

