version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          pwd
          ls -l
          ./build.sh
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          export BASE_VERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo-container?circle-token=${CIRCLE_TOKEN}&limit=100&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "package_navajo")][0].build_num')
          export MINORVERSION=3.3
          export VERSION=${MINORVERSION}.${BASE_VERSION}
          docker-compose up -d
          echo "Compose completed"
          date
          sleep 60
          echo "Sleep completed at:"
          date
          mkdir surefire-reports
          docker run -v $PWD/surefire-reports:/surefire-reports -e URL=http://navajo:8181 --network project_default dexels/navajo.example.test:latest
      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: surefire-reports
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - run: |
          export NAVAJOEXAMPLEBUILDNR=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo.example?circle-token=${CIRCLE_TOKEN}&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "build")][0].build_num')
          echo "Navajo Build nr: ${NAVAJOEXAMPLEBUILDNR}"
          echo "export NAVAJOEXAMPLEBUILDNR=$NAVAJOEXAMPLEBUILDNR" >> $BASH_ENV
          echo "Image: ${IMAGE}:${MINORTAG}.${NAVAJOEXAMPLEBUILDNR}"
#      - gcp-gke/install
#      - gcp-gke/init
#      - gcp-gke/rollout-image:
#          deployment: navajo
#          container: navajo
#          cluster: standard-cluster-1
#          image: ${IMAGE}:${MINORTAG}.${NAVAJOEXAMPLEBUILDNR} # change version when updating
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
